services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: $DATABASE_DB
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_HOST: $DATABASE_HOST
    ports:
      - "5432:$DATABASE_PORT"