version: "3.9"
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      PORT: $PORT
      BCRYPT_ROUNDS: $BCRYPT_ROUNDS
      JWT_SECRET: $JWT_SECRET
      DATABASE_DB: $DATABASE_DB
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_HOST: $DATABASE_HOST
    #   NODE_ENV: $NODE_ENV
    depends_on:
      - postgres
    ports:
      - $PORT:$PORT
    # network_mode: host
    volumes:
      - .:/app
  postgres:
    image: postgres:14
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: $DATABASE_DB
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_HOST: $DATABASE_HOST
    ports:
      - "5432:$DATABASE_PORT"
    # network_mode: host
